import { useMemo, type ComponentProps } from "react";
import type { I18nProvider } from "@refinedev/core";
import { DocumentTitleHandler } from "@refinedev/react-router";
import { useTranslation } from "react-i18next";
import { useAppResources } from "./resources";

const APP_TITLE = "Prevent Auto Mecanica CRM";

type DocumentTitleHandlerOptions = Parameters<
  NonNullable<ComponentProps<typeof DocumentTitleHandler>["handler"]>
>[0];

type DocumentTitleStrategy = (
  options: DocumentTitleHandlerOptions,
) => string | null;

const pageTitleStrategy: DocumentTitleStrategy = ({ autoGeneratedTitle }) => {
  const [pageTitle] = autoGeneratedTitle
    .split("|")
    .map((part) => part.trim())
    .filter(Boolean);

  return pageTitle ? `${pageTitle} | ${APP_TITLE}` : null;
};

const fallbackTitleStrategy: DocumentTitleStrategy = () => APP_TITLE;

const DOCUMENT_TITLE_STRATEGIES: DocumentTitleStrategy[] = [
  pageTitleStrategy,
  fallbackTitleStrategy,
];

export const appDocumentTitleHandler = (
  options: DocumentTitleHandlerOptions,
) => {
  for (const strategy of DOCUMENT_TITLE_STRATEGIES) {
    const result = strategy(options);
    if (result) {
      return result;
    }
  }

  return APP_TITLE;
};

export const useAppBootstrap = () => {
  const { t, i18n } = useTranslation();
  const resources = useAppResources(t);

  const i18nProvider = useMemo<I18nProvider>(
    () => ({
      translate: (
        key: string,
        params?: string | Record<string, unknown>,
        defaultMessage?: string,
      ) => {
        const resolvedDefaultMessage =
          typeof params === "string" && typeof defaultMessage === "undefined"
            ? params
            : defaultMessage;
        const resolvedParams =
          typeof params === "string" ? undefined : params;

        return t(key, {
          ...(resolvedParams ?? {}),
          defaultValue: resolvedDefaultMessage,
        });
      },
      changeLocale: (lang: string) => i18n.changeLanguage(lang),
      getLocale: () => i18n.language,
    }),
    [i18n, t],
  );

  return {
    resources,
    i18nProvider,
    documentTitleHandler: appDocumentTitleHandler,
  };
};
